# ベースイメージ
FROM node:20-alpine

# 作業ディレクトリ作成
WORKDIR /app

# package.json と package-lock.json をコピー
COPY package*.json ./

# 依存関係インストール
RUN npm install

# アプリケーションソースをコピー
COPY src ./src
COPY webpack.common.js webpack.prod.js webpack.dev.js .babelrc tsconfig.json ./

# ビルド
RUN npm run build

# ビルド成果物を nginx などで配信する場合
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html/dist
COPY index.html /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
